name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: |
          git config --global user.email "isha.sangani@outlook.com"
          git config --global user.name ${{ secrets.GH_TOKEN }}
          npm install
          npm install gh-pages --save-dev
          npm run build
          npm run deploy
