name: Deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          git config --global url.https://${{ secrets.GH_TOKEN }}@github.com/.insteadOf https://github.com/
          git config --global user.email "isha.sangani@outlook.com"
          git config --global user.name "isha-san"
          npm install
          npm install gh-pages --save-dev
          npm run build
          npm run deploy
        env:
          REACT_APP_SPARTINA: ${{ vars.REACT_APP_SPARTINA }}
